apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    database: metrics
    user: telegraf
    password: telegraf
    url: http://influxdb:8086
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
